# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TEST ENV - Build and deploy Node.js app to Azure Web App - promiseweb

on:
  push:
    branches:
      - development
      - 'test/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: npm install, build, and test in backend
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      - name: npm install, build and test in frontend
        run: |
          npm ci
          npm run build --if-present
        working-directory: ./frontend

      - name: Zip artifact for deployment
        run: Compress-Archive package.json, web.config, ./frontend/build release.zip
      - name: Update Zip artifact for deployment
        run: Compress-Archive -Update ./serverBuild/* release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: UnZip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'promiseweb'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B8C9F3F802FD448F84A332123733E23D }}
          package: .

      - name: Delete zip package
        run: rm release.zip

  test:
    needs: deploy
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Playwright
      working-directory: ./frontend
      run: npx playwright install chromium --with-deps

    - name: Run Playwright basic tests
      working-directory: ./frontend
      run: npx playwright test tests/basicTests
      env:
        PLAYWRIGHT_TEST_BASE_URL: https://promiseweb.azurewebsites.net/
        
    - name: Run Playwright playing game tests
      working-directory: ./frontend
      run: npx playwright test tests/playingGame --workers=7
      env:
        PLAYWRIGHT_TEST_BASE_URL: https://promiseweb.azurewebsites.net/
